### ISSUE TITLE
加了新属性后如何使vscode支持该属性

### ISSUE THREAD

**Issue by Mr-sgreen** [NervJS/taro-plugin-inject#1]
给View组件加了自定义属性data-title后，在使用View的时候View组件没有这个属性，vscode报错，如何修正
![image](https://user-images.githubusercontent.com/12498468/124948110-fe122f00-e042-11eb-843b-973ecf416744.png)
![image](https://user-images.githubusercontent.com/12498468/124948422-429dca80-e043-11eb-9251-c7d70683f995.png)

**Comment by Chen-jj** [comment]
使用 TS 的模块补充 (module augmentation)：https://docs.taro.zone/docs/platform-plugin-how#%E7%B1%BB%E5%9E%8B

**Comment by Mr-sgreen** [comment]
> 使用 TS 的模块补充 (module augmentation)：https://docs.taro.zone/docs/platform-plugin-how#%E7%B1%BB%E5%9E%8B

好的，感谢，补充下一个比较Low的方法：
```typescript
//tsconfig.json
{
  "compilerOptions": {
     "typeRoots": ["src/global.d.ts"],
   }
}

//global.d.ts
declare module '@tarojs/components' {
  export * from '@tarojs/components/types/index';

  //修改的Props
  import { ComponentType } from 'react';
  import { ViewProps as OldViewProps } from '@tarojs/components/types/View';

  interface ViewProps extends OldViewProps {
    dataTitle?: string;
  }

  declare const View: ComponentType<ViewProps>;

  export { View };
}
```

**Comment by Chen-jj** [comment]
@Mr-sgreen 有空可以提个 PR 写到 README 里～

**Comment by Mr-sgreen** [comment]
> @Mr-sgreen 有空可以提个 PR 写到 README 里～

已提~，感谢抽空解答
