### ISSUE TITLE
在我的项目中配置了不生效

### ISSUE THREAD

**Issue by dufemeng** [NervJS/taro-plugin-inject#10]
Taro CLI 版本为3.3.17，插件版本为1.0.1

配置如下：
plugins: [
    ['@tarojs/plugin-inject', {
      components: {
        // 为 Text 组件新增了 'x-props' 属性和 'bindYEvent' 事件
        Navigator: {
          'x-props': "'hello'",
          bindYEvent: ''
        },
      },
    }]
  ],

对应的Navigator 组件并未有这个属性

**Comment by Chen-jj** [comment]
看 `base.wxml` 里的 `<template name="tmpl_0_navigator">` 是成功增加了的：

![image](https://user-images.githubusercontent.com/11807297/156870173-328f6c1d-0343-4691-967f-81600c9fcd40.png)
