### ISSUE TITLE
export * from 'undefined'

### ISSUE THREAD

**Issue by OneKissAndOneShot** [NervJS/taro-plugin-inject#11]
dist/components-react.js 
中from  undefined报错

**Comment by Yuwenbinjie** [comment]
![image](https://user-images.githubusercontent.com/32625660/158515505-f6eb271a-3cdf-4640-b858-a0e64fb47b42.png)
遇到了相同的问题，请问怎么解决 的？

**Comment by Yuwenbinjie** [comment]
>  ##
遇到了相同的问题，请问怎么解决 的？
![image](https://user-images.githubusercontent.com/32625660/158516223-f17b7718-7f21-4a92-aeca-d81395f15c31.png)

**Comment by Yuwenbinjie** [comment]
> 芋头3.4.1

遇到了相同的问题，请问怎么解决 的？
![image](https://user-images.githubusercontent.com/32625660/158516367-3242e09d-bbae-424a-89f2-4bf425b93926.png)
