### ISSUE TITLE
打包编译报错：Module not found: Can't resolve 'undefined' in '/Users/bytedance/Desktop/project/haidian_hospital_xcx/node_modules/@tarojs/plugin-inject/dist'

### ISSUE THREAD

**Issue by Yuwenbinjie** [NervJS/taro-plugin-inject#12]
![image](https://user-images.githubusercontent.com/32625660/158515569-d2dbb7a9-9f01-4234-ab2b-4cdb49b7d98f.png)

**Comment by Yuwenbinjie** [comment]
@tarojs/plugin-inject": "^1.0.1
使用方法：
![image](https://user-images.githubusercontent.com/32625660/158515897-ef5e6f8b-ce2c-4426-bc52-d4517e20cfdd.png)

**Comment by OneKissAndOneShot** [comment]
taro最新版应该是已经修复这个BUG了

**Comment by OneKissAndOneShot** [comment]
> 

taro最新版已经修复
