### ISSUE TITLE
引入 taro-plugin-inject 编译后报错

### ISSUE THREAD

**Issue by yuluotuxi** [NervJS/taro-plugin-inject#3]
![image](https://user-images.githubusercontent.com/23314558/128280802-fcd51f84-5349-4d3b-91b8-a40b5ffdeb08.png)

配置如下：
`
plugins: [
    ['@tarojs/plugin-inject', {
      components: {
        // 为 Map 添加 theme
        Map: {
          'theme': '',
        }
      }
    }]
  ],
`
![image](https://user-images.githubusercontent.com/23314558/128280924-57c8e5a0-d68f-4abc-8f20-bc6c24842838.png)

**Comment by Chen-jj** [comment]
已修复
