### ISSUE TITLE
如何新增一个taro不支持的组件呢？

### ISSUE THREAD

**Issue by MLYC** [NervJS/taro-plugin-inject#8]
比如百度新增了login组件，https://smartprogram.baidu.com/docs/develop/component/login/
taro还未适配，这时候应该如何使用这一组件？

**Comment by Chen-jj** [comment]
文档已经写清楚了吧

**Comment by DaZiYuan** [comment]
同问，我也想增加这个组件，希望能给一个demo
https://developers.weixin.qq.com/miniprogram/dev/component/share-element.html

**Comment by DaZiYuan** [comment]
> 该插件文档只是写了为组件新增属性，新增组件并没有提及，Taro文档里面说可以使用该插件新增组件，但实际测试并没有用，最终并没有按预期渲染组件@Chen-jj

请问找到方案了吗，我也遇到同样的问题了

**Comment by xdoer** [comment]
先按照文档配一下，然后如下，在代码里写一下。 @MLYC @DaZiYuan 

```tsx
import { View } from '@taro/component'

// @ts-ignore
const ShareElement = 'share-element'

export default () => {
   return (
      <View>
            <ShareElement />
     </View>
   )
}
```

**Comment by m2rbl3** [comment]
> 

请问`ShareElement`的声明有什么用呢？我试了一下什么都没渲染

**Comment by xdoer** [comment]
@m2rbl3 你有在代码里按照文档里配置一下吗？看一下这篇文档 https://taro-docs.jd.com/taro/docs/platform-plugin-base#34-%E7%BC%96%E5%86%99-components-reactts

**Comment by m2rbl3** [comment]
> @m2rbl3 你有在代码里按照文档里配置一下吗？看一下这篇文档 https://taro-docs.jd.com/taro/docs/platform-plugin-base#34-%E7%BC%96%E5%86%99-components-reactts

@xdoer 除了taro的config还有哪里要配置吗?我是这样配的

taro的config
```js
 plugins: [
    ['@tarojs/plugin-inject', {
      components: {
        Component: {
          is: ''
        },
        Component2: {
          is: ''
        },
        component: {
          is: ''
        }
      }
    }]
  ],
```
然后在页面组件上:
```js
render() {
   const Component2 = 'component'; // 支付宝端动态插件要用component标签，与react的Component冲突，所以改了下变量名

   return (
        <Block>
            <Component2 is='dynamic-plugin://202100xxx9035/xx' />
            <component is='dynamic-plugin://202100xxx9035/xx' />
        </Block>
    )
}
```

**Comment by xdoer** [comment]
按照这样配置，应该就可以生效了。我是微信小程序，虽然控制台有打印警告，但是是有效的。

支付宝无效的话，你可以尝试改一下 `node_modules/@tarojs/plugin-platform-alipay/dist/components-react.js` 文件, 把你需要的组件写一下。 

如果写在这个文件生效了的话，而写在代码无效。你可以需要 patch-package 之类的包，来处理一下。

**Comment by m2rbl3** [comment]
@xdoer 好的，感谢
